<?php

/**
 * @file
 * My first module. It doesn't do much more than change a comment
 *  form label.
 */

/**
 * Implements hook_menu().
 *
 * Defines a path to our configuration page.
 */
function myfirstmodule_menu() {
  $items['admin/config/user-interface/myfirstmodule'] = array(
    'title' => 'My first module configuration',
    'description' => 'Configuration page for the My First Module module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_myfirstmodule_settings'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Custom function that returns the settings page form.
 */
function _myfirstmodule_settings() {
  $form = array();

  $form['myfirstmodule_author_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Comment author label'),
    '#description' => t('Enter an alternate label for the comment author field'),
    '#default_value' => variable_get('myfirstmodule_author_label', 'Your name'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['myfirstmodule_subject_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Comment subject label'),
    '#description' => t('Enter an alternate label for the comment subject field'),
    '#default_value' => variable_get('myfirstmodule_subject_label', 'Subject'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 *
 * This updates the "username" comment form label.
 */
function myfirstmodule_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'comment_node_article_form') {
    if (user_access('view new comment form labels')) {
      $form['author']['_author']['#title'] = variable_get('myfirstmodule_author_label', 'Your name');
      $form['subject']['#title'] = variable_get('myfirstmodule_subject_label', 'Topic');
    }
  }
}

/**
 * Implements hook_permissions().
 *
 * This defines a new permission for our module.
 */
function myfirstmodule_permission() {
  return array(
    'view new comment form labels' => array(
      'title' => t('View new comment form labels'),
      'description' => t('Allows users to use the alternate comment for labels.'),
    ),
  );
}